import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "./components/navbar";

const geistSans = localFont({
  src: "./fonts/Geogrotesque Sharp VF TRIAL.woff",
  variable: "--font-geist-sans",
  weight: "100 100",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased bg-gray-100 scrollbar overflow-x-hidden text-gray-800`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
